services:
  redis:
    image: redis:alpine
    container_name: game-logs-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - game-logs-network

  log_collector:
    build:
      context: ./log_collector
      dockerfile: Dockerfile
    container_name: game-logs-collector
    volumes:
      - ./config.py:/app/config.py
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
    networks:
      - game-logs-network

  vip_rewards:
    build:
      context: ./vip_rewards
      dockerfile: Dockerfile
    container_name: game-vip-rewards
    volumes:
      - ./config.py:/app/config.py
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
    networks:
      - game-logs-network

  melee_rewards:
    build:
      context: ./melee_rewards
      dockerfile: Dockerfile
    container_name: game-melee-rewards
    volumes:
      - ./config.py:/app/config.py
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
    networks:
      - game-logs-network

networks:
  game-logs-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
